vim.opt.rtp:append(vim.fn.getcwd())
local cwd = vim.fn.getcwd()
local root = vim.fn.tempname()
vim.fn.mkdir(root, "p")
assert(vim.system({ "git", "init", "-q", root }):wait().code == 0)
local ok, err = xpcall(function()
  vim.fn.chdir(root)
  require("agent-lens").setup({ enabled = false })
  require("agent-lens.health").check()
end, debug.traceback)
vim.fn.chdir(cwd)
vim.fn.delete(root, "rf")
assert(ok, err)
print("health check OK")
vim.cmd("qa!")
